[toolchain]
channel = "1.85.1"
components = ["rust-src", "rust-analyzer", "clippy", "rustfmt"]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-gnu",
  "aarch64-unknown-linux-musl",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "x86_64-pc-windows-gnu",
  "i686-pc-windows-gnu",
  "aarch64-linux-android",
  "armv7-linux-androideabi",
]
